apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
