apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /persisted-volume/apps/home-assistant/config
