apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - custom-resource-definition.yaml
  - service-account.yaml
  - config-map.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - role.yaml
  - service.yaml
  - deployment.yaml
  - mutating-webhook-configuration.yaml
  - validating-webhook-configuration.yaml
  - cluster-issuer.yaml
commonLabels:
  app: cert-manager
