apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - service.yaml

commonLabels:
  app: nginx-proxy-manager
