apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-proxy-manager-data-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /persisted-volume/infrastructure/nginx-proxy-manager/data
